from pathlib import Path
import json,hashlib,subprocess,re,datetime,shutil
root=Path(__file__).resolve().parents[1]
for name,start in [(root.name,'97d4248' if root.name=='NEMA14_RP2040' else '2d69fc4')]:
 r=Path('/workspace')/name;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads((r/p).read_text());board=r/'artifacts/board.circuit.json';j=read('artifacts/board.circuit.json');bs=sha(board);mech=read('artifacts/mechanical/mechanical-review.json');h=mech['service_harness'];assert mech['board_sha256']==bs
 assert read('artifacts/validation/service-motor-inside-board.json')['source_sha256']==bs
 assert all(v['after_0p2_outline_0p1_placement_mm']>0 for v in h['full_connector_inside_board_screen'])
 assert all(mech[k] for k in ['nominal_no_component_intersections','nominal_no_fastener_intersections','nominal_no_carrier_intersections','nominal_no_plug_envelope_intersections']);assert h['nominal_wire_collision_free']
 bbox=mech['mounted_assembly_bbox_mm'];size=[bbox[i+3]-bbox[i]for i in range(3)]
 p=r/'docs/mechanical-fit.md';s=p.read_text();s=re.sub(r'The computed complete motor/carrier/harness/two-cable reserved envelope.*?Lower splices/factorylead adaptation remain an actual-motor qualification gate\.',f'The complete nominal reserved motor/carrier/harness/two-cable envelope is {size[0]:.2f} × {size[1]:.2f} × {size[2]:.2f} mm (X/Y/Z). Bounds relative to PCB midplane: X[{bbox[0]:.3f},{bbox[3]:.3f}], Y[{bbox[1]:.3f},{bbox[4]:.3f}], Z[{bbox[2]:.3f},{bbox[5]:.3f}]. Positive Y includes the reserved USB cable bend; negative Y includes the separate factory-lead loop. Host space must include these bounds plus manufacturing tolerances, cable motion and installation/removal access. Factory lead and splice integration remain physical qualification gates.',s,flags=re.S);p.write_text(s)
 assertions={'pilot_pattern_remaining_radial_mm':.525-.354-.126,'tail_barrier_remaining_mm':h['tail_to_barrier_after_0p15_pcb_0p05_carrier_0p05_sheet_allowances_mm'],'usb_body_pair_remaining_mm':mech['usb_same_edge_cable_fit']['after_0p1mm_placement_per_port_mm'],'usb_outward_registration_remaining_mm':.4-.1-.2,'bulk_max_envelope_to_outline_after_0p2_outline_0p1_placement_mm':mech['bulk_capacitor_manufacturer_maximum_envelope_screen']['body_to_board_nominal_edge_lower_bound_mm']-.3,'minimum_fastener_to_component_after_0p35_play_0p1_placement_0p05_carrier_mm':min(e['minimum_all_component_distance_lower_bound_mm']for e in mech['pcb_fastener_all_component_lower_bounds'])-.5,'extension_to_carrier_after_0p2_routing_0p05_OD_0p05_machining_mm':min(e['distance_mm']for e in h['wire_clearance_checks']if e['wire'].startswith('Wire_')and e['other']=='carrier')-.3,'extension_to_motor_after_0p2_routing_0p05_OD_0p1_body_0p126_pilot_0p05_machining_mm':min(e['distance_mm']for e in h['wire_clearance_checks']if e['wire'].startswith('Wire_')and e['other']=='motor')-.526}
 assertions['full_header_edge_after_0p2_outline_0p1_placement_mm']=min(v['after_0p2_outline_0p1_placement_mm']for v in h['full_connector_inside_board_screen'])
 assert min(assertions.values())>0,assertions
 tolerance={'board_sha256':bs,'mechanical_report_sha256':sha(r/'artifacts/mechanical/mechanical-review.json'),'bounded_clearance_screens_mm':assertions,'procurement_and_assembly_allowances_are_requirements_not_measurements':True,'factory_lead_OD_material_bend_and_placement_bounds_verified':False,'qualification':'Prototype screen only; actual motor revision, lead stock, model discrepancy, tolerances/materials/retention and fit must be qualified.'};(r/'artifacts/mechanical/service-tolerance-review.json').write_text(json.dumps(tolerance,indent=2)+'\n')
 p=r/'docs/mechanical-fit.md';p.write_text(p.read_text() if 'Final bounded clearance screen is in' in p.read_text() else p.read_text()+'\nFinal bounded clearance screen is in `artifacts/mechanical/service-tolerance-review.json`; all stated placement/routing/machining allowances are assembly requirements, not measurements. Complete harness/carrier drawings are in `artifacts/assembly/harness-carrier-drawings.pdf`.\n')
 shutil.copyfile(board,r/'index.circuit.json')
 old=json.loads(subprocess.check_output(['git','show',start+':artifacts/board.circuit.json'],cwd=r))
 def graph(records):
  sc={e['source_component_id']:e['name']for e in records if e['type']=='source_component'};ports=[e for e in records if e['type']=='source_port'and 'pin_number'in e];groups={}
  for p in ports:groups.setdefault(p.get('subcircuit_connectivity_map_key')or('NC',sc[p['source_component_id']],str(p['pin_number'])),[]).append((sc[p['source_component_id']],str(p['pin_number'])))
  return {(sc[p['source_component_id']],str(p['pin_number'])):sorted(groups[p.get('subcircuit_connectivity_map_key')or('NC',sc[p['source_component_id']],str(p['pin_number']))])for p in ports}
 a,b=graph(old),graph(j);assert a==b,'Physical pin connectivity changed'
 inv={'requested_start_commit':start,'current_saved_board_sha256':bs,'source_physical_ports_before':len(a),'after':len(b),'changes':[],'all_source_port_net_identities_preserved':True,'method':'Compare every numbered component pin and its complete connected-pin equivalence class; independent of generated net IDs.'};(r/'artifacts/validation/service-pin-net-invariance.json').write_text(json.dumps(inv,indent=2)+'\n')
 for f,key in [('artifacts/manufacturing/audit.json','source_sha256'),('artifacts/manufacturing/via-paste-inspection.json','source_sha256'),('artifacts/physical-connectivity.json','sha256'),('artifacts/trace-width-review.json','sha256'),('artifacts/validation/service-outer-power-policy.json','sha256'),('artifacts/validation/service-outer-power-cam.json','source_sha256'),('artifacts/assembly/assembly-review.json','source_sha256'),('artifacts/validation/service-schematic-ui/review.json','board_sha256')]:assert read(f)[key]==bs,(name,f)
 assert read('artifacts/validation/service-outer-power-policy.json')['checksPassed'];assert read('artifacts/validation/service-outer-power-cam.json')['checksPassed'];assert read('artifacts/manufacturing/audit.json')['status']=='PASS';assert read('artifacts/manufacturing/via-paste-inspection.json')['status']=='PASS';assert not read('artifacts/physical-connectivity.json')['disconnectedNets'];assert not read('artifacts/trace-width-review.json')['errors'];assert not read('artifacts/drc-report.json')['errors'];assert 'No shorts detected'in(r/'artifacts/validation/service-shorts.txt').read_text();assert not json.loads((r/'artifacts/validation/service-silkscreen.txt').read_text())['errors']
 cli=read('artifacts/validation/service-cli-results.json');assert all(c['exit_code']==0 for c in cli['commands']if c['name']!='placement');assert cli['prepared_source_sha256']==sha(r/'artifacts/final-source.circuit.json')
 gates=['Winding current/balance/torque and sense/return parasitics including low-VREF A4988 accuracy','USB enumeration/ROM programming/application firmware and15V PD behavior','All DATA/PD power orders, brownout/reset/OE/ADC pin limits and backfeed','Regeneration/hot-plug clamp energy and exact selected protection data','Mounted temperatures and Holtek worst-load thermal/transient margin','Complete motor/carrier/harness/two-cable physical fit/retention/host loading','Factory JST post/key/spring CAD versus generic supplier model discrepancy','Biased/aged effective capacitor values and converter stability/current margins','Temperature/material/splice certificates and factory motor lead stock','Supplier pickup/rotation preview, TypeVI off-pad fill, TypeVII SMT cap and fine-drill/stencil process acceptance']
 state={'schema':'pcba-program-state-v1','project_id':read('package.json')['name'],'updated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'offline_service_review':'PASS_WITH_DISCLOSED_ADVISORIES_AND_MODEL_DATA_GATES','manufacturing_release':False,'hardware_tested':False,'outer_motor_pd_policy_passed':True,'outer_motor_pd_actual_cam_passed':True,'pcb_style_cli_status':'UNAVAILABLE_IN_INSTALLED_CLI; attempted exit retained','publication_authorized':True,'publication_receipt':'artifacts/validation/service-published-release.json (only valid after actual publication)','remaining_qualification_items':gates,'placement_cli_exit':next(c['exit_code']for c in cli['commands']if c['name']=='placement'),'placement_advisories_suppressed':False,'electrical_and_physical_qualification':'BLOCKED','historical_reports':'Earlier manifests, SES replay and publication receipts do not validate this changed revision.'};(r/'.pcba-workflow/program-state.json').write_text(json.dumps(state,indent=2)+'\n')
 if name=='NEMA14_RP2040':
  p=r/'docs/engineering-review.md';p.write_text(p.read_text() if 'Revised USB_DM and QSPI_SS transitions have explicit' in p.read_text() else p.read_text()+'\nRevised USB_DM and QSPI_SS transitions have explicit ground-return stitches at(6.625,12.5) and(−1,9.425), approximately1.08/1.10mm from the signal via. Actual inner1 cut analysis retains all raw overlaps and distinguishes own signal transition antipads; no foreign-cut centerline crossing or copper over the guarded power-bridge cut is accepted. Geometric return-path screening does not qualify USB/QSPI signal integrity or EMC.\n')
 selected=[Path('index.circuit.tsx'),Path('index.circuit.json'),Path('package-lock.json'),Path('tscircuit.config.json'),Path('.pcba-workflow/program-state.json')]
 for directory in ['src','scripts','references','imports/supplier','docs']:
  selected.extend(p.relative_to(r)for p in(r/directory).rglob('*')if p.is_file()and '__pycache__'not in p.parts and p.suffix!='.pyc')
 for pattern in ['artifacts/board.circuit.json','artifacts/final-source.circuit.json','artifacts/nema14-gerbers.zip','artifacts/manufacturing-raw.zip','artifacts/bom.csv','artifacts/pick_and_place.csv','artifacts/source-bom.csv','artifacts/drc-report.json','artifacts/physical-connectivity.json','artifacts/trace-width-review.json','artifacts/jlcpcb-import-report.json','artifacts/supplier-cad-alignment.json','artifacts/schematic-a4.pdf','artifacts/schematic-a4-page-*.svg','artifacts/manufacturing/*','artifacts/assembly/*','artifacts/mechanical/*','artifacts/engineering/service-power-review.json','artifacts/validation/service-*','artifacts/validation/functional-*']:
  selected.extend(p.relative_to(r)for p in r.glob(pattern)if p.is_file()and p.name not in ['service-publication-provenance.json','service-published-release.json','service-publish-output.txt'])
 selected=sorted(set(selected));manifest={'schema':'nema14-inside-jst-review-manifest-v3','project':read('package.json')['name'],'requested_local_start_commit':start,'generated_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'saved_board_sha256':bs,'index_saved_board_byte_identical':sha(r/'index.circuit.json')==bs,'inventory_note':'Routing workflow intermediate reports are diagnostic history, not final acceptance. Acceptance reports must be bound to the final saved board.', 'outer_motor_pd_policy':read('artifacts/validation/service-outer-power-policy.json'),'outer_motor_pd_actual_cam':read('artifacts/validation/service-outer-power-cam.json'),'full_jst_inside_board':read('artifacts/validation/service-motor-inside-board.json'), 'software_scope':'Current source/build/native connectivity/DRC/trace-width/actualCAM/drill/stencil/shorts, nativeA4 browser and mechanical installation screens. Historical files outside this list are not current acceptance evidence.','offline_checks':'PASS with retained native placement exit1 advisories and generic NPN ERC warning; exact generic header-post model discrepancy openly unresolved.','manufacturing_release':False,'physical_hardware_tested':False,'remaining_qualification_items':gates,'files_sha256':{str(p):sha(r/p)for p in selected}};(r/'artifacts/validation/engineering-review-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
 print(name,'final board',bs,'manifestfiles',len(selected),'host envelope',size,flush=True)
